# -*- coding: utf-8 -*-
"""Fudacao_bradesco.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NOz2Y3r3E7xLtkoB4j6TpCQKy2VTcq1o
"""

#importações necessárias

import sqlite3
import pandas as pd
import csv

#Caminho do arquivo
raw_data_path = 'o caminho do seu arquivo'

!head '/content/inep_indicadores_educacionais_brasil.csv.gz'

#Lendo o arquivo com o pandas
dF= pd.read_csv(raw_data_path, sep=',', low_memory=False)

conn1 = sqlite3.connect('Nome do data base')

#Criando tabela dentro do database
dF.to_sql('nome da tabela que você vai criar',conn1,if_exists='replace',index=False)

#Código para conseguir rodar querys
query = "PRAGMA table_info('nome da tabela criada')"
result = pd.read_sql(query,conn1)
print(result)

#Consulta no sql
query = """
SELECT rede,
CAST(ano AS INTEGER) AS ano,
CAST(taxa_abandono_em_3_ano AS INTEGER) AS abandono

FROM Indicadores

WHERE ano >= 2016
and ano NOT LIKE 2023
and rede IN('estadual')
GROUP BY ano
ORDER BY ano, abandono DESC
"""

result = pd.read_sql(query,conn1)
result

result.to_csv('nome do csv que você vai criar', index=False)

# Commented out IPython magic to ensure Python compatibility.
#importando
import pandas as pd
import numpy as np
from numpy.random import randn
# %matplotlib inline

#Lendo a tabela
tb = pd.read_csv('nome da sua tabela')
tb1 = open("nome da sua tabela").readlines()

#Importando a biblioteca
import matplotlib.pyplot as plt

#Laço para criar o eixo x e o eixo y
x = []
y = []
for i in range(len(tb1)):
  if i != 0:
    linha = tb1[i].split(",")
    x.append(linha[1])
    y.append(int(linha[2]))
# Plotando o gráfico
plt.plot(x,y)
plt.title("Título")
plt.xlabel("eixo x")
plt.ylabel("eixo y")
plt.grid(color = 'w', linestyle='--', linewidth=0.5)
plt.show()

